[package]
name = "notal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imagine = "0.0.5"
comrak = "0.10"
wgpu = "0.12.0"
winit = "0.26.1"