[package]
name = "notal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl33 = "0.2.1"
imagine = "0.0.5"
comrak = "0.10"
beryllium = "0.2.0-alpha.4"
